carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    # the add_cart url is added so that the user's cart increased when he adds a cart
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    # This is the remove cart function which removes one particular product at a time
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    # This here removes everything from the cart
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    # this here is the checkout url
    path('checkout/', views.checkout, name='checkout'),
    
]

greatcart/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('category.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views


# the namespace for the store app

app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
]

carts/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account

# Create your models here.


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)
    
    
    def __str__(self) -> str:
        return self.cart_id
    
    
class CartItem(models.Model):
    # this here adds the foreign key to connect each user to a specific cart item
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)
    
    
    def sub_total(self):
        return self.product.price * self.quantity
    
    
    def __str__(self) -> str:
        return str(self.variations)

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required


from store.models import Product, Variation
from carts.models import *
from django.http import HttpResponse

# Create your views here.

# first we have to get the cart_id from the session
# That session is  what we need when a user adds a product to cart. That 'session id' is actually important
def _cart_id(request):
    """
    Here, a session is actually checked tp see if the user that requests a thing has a session_key
    if it does, fine, no, then create a new session for the user and return it
    
    """
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id) #What this does is it retrives a specific product by it id. it checks whether it is there
    
    
    if current_user.is_authenticated:
        product_variation = []
        # Checks to see if the request submitted is a get or post
        if request.method == 'POST':
            # this here after the user submits the data, it comes to the backend which is assigned to the color and size variables
            # color = request.POST['color']
            # size = request.POST['size']
            # print(color, size)
            
            # the code above, shows that what it does it just that it gets the value submitted by the client; but there is a simpler method of doing this
            for item in request.POST:
                # here it iterates and assigns the 'key' to the request, to the key variable
                key = item
                # this here gets the value of the key and assigns it to the value variable
                value = request.POST[key]
                try:
                    # checking what the user submits matches the variation in our database together with the product
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    #since we can have many variations in the cartitem,  we append the items and store them in a list
                    product_variation.append(variation)
                    # print(product_variation)
                except Variation.DoesNotExist:
                    pass
                
        # try:
        #     cart = Cart.objects.get(cart_id=_cart_id(request))
            
        # except Cart.DoesNotExist:
        #     cart = Cart.objects.create(
        #         cart_id=_cart_id(request)
        #     )
        
        # cart.save()
        
        
        # first, we have to check if cartitem exists or not
        # since it is not grouping it in the cartitems, so let's do it now, but we have to make the try block into if-else statement
        
        
        # check if cart_item exists
        
        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exists:
            # assigning the cart item to the current user
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            
            
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)
                
            if product_variation in ex_var_list:
                # we are going to look for the id and increased it
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            
            else:
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
                
                
        else:
            cart_item = CartItem.objects.create(product=product, quantity= 1, user=current_user)
            if len(product_variation) > 0 :
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('carts:cart')
            
    # return HttpResponse(cart_item.quantity)
    # exit() Here it checks for the quantity to see that the product is actually add to cart
    
    
    # end of the current user and the start of the anonymous user
    
    
    else:
        product_variation = []
    # Checks to see if the request submitted is a get or post
        if request.method == 'POST':
            # this here after the user submits the data, it comes to the backend which is assigned to the color and size variables
            # color = request.POST['color']
            # size = request.POST['size']
            # print(color, size)
            
            # the code above, shows that what it does it just that it gets the value submitted by the client; but there is a simpler method of doing this
            for item in request.POST:
                # here it iterates and assigns the 'key' to the request, to the key variable
                key = item
                # this here gets the value of the key and assigns it to the value variable
                value = request.POST[key]
                try:
                    # checking what the user submits matches the variation in our database together with the product
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    #since we can have many variations in the cartitem,  we append the items and store them in a list
                    product_variation.append(variation)
                    # print(product_variation)
                except Variation.DoesNotExist:
                    pass
                
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id=_cart_id(request)
            )
        
        cart.save()
        
        
        # first, we have to check if cartitem exists or not
        # since it is not grouping it in the cartitems, so let's do it now, but we have to make the try block into if-else statement
        
        
        # check if cart_item exists
        
        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            
            
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)
                
            if product_variation in ex_var_list:
                # we are going to look for the id and increased it
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            
            else:
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
                
                
        else:
            cart_item = CartItem.objects.create(product=product, quantity= 1, cart=cart)
            if len(product_variation) > 0 :
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('carts:cart')
            
# return HttpResponse(cart_item.quantity)
# exit() Here it checks for the quantity to see that the product is actually add to cart




# the cart_item_id is added so as to delete that very product, not just any product.
# fixing the remove button for when logged in user
def remove_cart(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    
    
    try:
        # here the item is checked together with thw product, cart and the id of the cart_item_id
        # first we have to check to see whether user is authenticated
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            # here it should decrease the product based on the anonymous user.
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        
        if cart_item.quantity > 1 :
            cart_item.quantity -= 1
            cart_item.save()
        
        else:
            cart_item.delete()
    except:
        pass 
    
    return redirect('carts:cart')


def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    
    try:
        # samething for the remove all button
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(user=request.user, product=product, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(cart=cart, product=product, id=cart_item_id)
    except:
        pass
    
    cart_item.delete()

carts/templates/carts/cart.html
{% extends 'category/base.html' %}
{% load static %}



{% block content %}
<section class="section-content padding-y bg">
	<div class="container">

		<!-- ============================ COMPONENT 1 ================================= -->
		{% if not cart_items %}
		<h2 class="text-center">Your Shopping Cart Is Empty</h2>
		<br>
		<div class="text-center">
			<a href="{% url 'store:store' %}" class="btn btn-primary">Continue Shopping</a>
		</div>
		{% else %}
		<div class="row">
			<aside class="col-lg-9">
				<div class="card">
					<table class="table table-borderless table-shopping-cart">
						<thead class="text-muted">
							<tr class="small text-uppercase">
								<th scope="col">Product</th>
								<th scope="col" width="120">Quantity</th>
								<th scope="col" width="120">Price</th>
								<th scope="col" class="text-right" width="200"> </th>
							</tr>
						</thead>
						<tbody>
							{% for cart_item in cart_items %}
							<tr>
								<td>
									<figure class="itemside align-items-center">
										<div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm">
										</div>
										<figcaption class="info">
											<a href="{{ cart_item.product.get_product_url }}" class="title text-dark">{{cart_item.product.product_name }}</a>
											<p class="text-muted small">
												{% if cart_item.variations.all %}
												{% for item in cart_item.variations.all %}
												{{ item.variation_category | capfirst }} : {{ item.variation_value |capfirst }} <br>
												{% endfor %}
												{% endif %}
											</p>
										</figcaption>
									</figure>
								</td>
								<td>
									<!-- col.// -->
									<div class="col">
										<div class="input-group input-spinner">
											<div class="input-group-prepend">
												<a href="{% url 'carts:remove_cart' cart_item.product.id cart_item.id %}"
													class="btn btn-light" type="button" id="button-plus"> <i
														class="fa fa-minus"></i> </a>
											</div>
											<input type="text" class="form-control" value="{{ cart_item.quantity }}">
											<div class="input-group-append">
												<form action="{% url 'carts:add_cart' cart_item.product.id %}"
													method="POST">
													{% csrf_token %}
													{% for item in cart_item.variations.all %}
													<input type="hidden" name="{{ item.variation_category }}"
														value="{{ item.variation_value }}">
													{% endfor %}
													<button type="submit" class="btn btn-light" type="button"
														id="button-minus"> <i class="fa fa-plus"></i> </button>
												</form>
											</div>
										</div> <!-- input-group.// -->
									</div> <!-- col.// -->
								</td>
								<td>
									<div class="price-wrap">
										<var class="price">$ {{ cart_item.sub_total }}</var>
										<small class="text-muted"> $ {{ cart_item.product.price }} each </small>
									</div> <!-- price-wrap .// -->
								</td>
								<td class="text-right">
									<a href="{% url 'carts:remove_cart_item' cart_item.product.id cart_item.id %}"
										onclick="return confirm('Are you sure you want to remove product from cart?')"
										class="btn btn-danger"> Remove</a>
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div> <!-- card.// -->

			</aside> <!-- col.// -->
			<aside class="col-lg-3">

				<div class="card">
					<div class="card-body">
						<dl class="dlist-align">
							<dt>Total price:</dt>
							<dd class="text-right">${{ total }}</dd>
						</dl>
						<dl class="dlist-align">
							<dt>Tax:</dt>
							<dd class="text-right"> $ {{ tax }}</dd>
						</dl>
						<dl class="dlist-align">
							<dt>Grand Total:</dt>
							<dd class="text-right text-dark b"><strong>$ {{ grand_total }}</strong></dd>
						</dl>
						<hr>
						<p class="text-center mb-3">
							<img src="{% static 'category/images/misc/payments.png' %}" height="26">
						</p>
						<a href="{% url 'carts:checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
						<a href="{% url 'store:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
					</div> <!-- card-body.// -->
				</div> <!-- card.// -->

			</aside> <!-- col.// -->


		</div> <!-- row.// -->
		{% endif %}
		<!-- ============================ COMPONENT 1 END .// ================================= -->

	</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}

carts/templates/carts/checkout.html
{% extends 'category/base.html' %}
{% load static %}



{% block content %}
<section class="section-content padding-y bg">
    <div class="container">

        <!-- ============================ COMPONENT 1 ================================= -->
        <div class="row">
            <aside class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title mb-4">Billing Address</h4>
                        <!-- this form here sends the product to the checkout page, but for one 
                             to use the checkout page, they need to login. When they log in, what
                             is in their cart gets lost due to the fact that the product_id/cart_item_id
                             isn't assigned to a user.
                        
                        -->
                        <form action="{% url 'carts:checkout' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col form-group">
                                    <label for="">First Name<span style="color: hsla(0, 100%, 50%, 0.89);">*</span></label>
                                    <input placeholder="First Name" type="text" name="first_name" class="form-control" required>
                                </div>
                                <div class="col form-group">
                                    <label for="">Last Name<span style="color: hsla(0, 100%, 50%, 0.89);">*</span></label>
                                    <input placeholder="Last Name" type="text" name="last_name" class="form-control" required>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col form-group">
                                    <label for="">Email<span style="color: hsla(0, 100%, 50%, 0.89);">*</span></label>
                                    <input placeholder="Email" type="email" name="email" class="form-control" required>
                                </div>
                                <div class="col form-group">
                                    <label for="">Phone Number<span style="color: hsla(0, 100%, 50%, 0.89);">*</span></label>
                                    <input placeholder="Phone Number" type="text" name="phone_number" class="form-control" required>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col form-group">
                                    <label for="">Address Line 1<span style="color: hsla(0, 100%, 50%, 0.89);">*</span></label>
                                    <input placeholder="Address Line 1" type="text" name="address_line_1" class="form-control" required>
                                </div>
                                <div class="col form-group">
                                    <label for="">Address Line 2</label>
                                    <input placeholder="Address Line 2" type="text" name="address_line_2" class="form-control">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col form-group">
                                    <label for="">City<span style="color: hsla(0, 100%, 50%, 0.89);">*</span></label>
                                    <input placeholder="City" type="text" name="city" class="form-control" required>
                                </div>
                                <div class="col form-group">
                                    <label for="">State<span style="color: hsla(0, 100%, 50%, 0.89);">*</span></label>
                                    <input placeholder="State" type="text" name="state" class="form-control" required>
                                </div>
                            </div>
                            <div class="form-row">
                                <label for="">Order Note</label>
                                <textarea name="order_name" rows="2" class="form-control"></textarea>
                            </div>
                        </div>
                    </div> <!-- card.// -->
                
            </aside> <!-- col.// -->
            <aside class="col-lg-6">
                
                <div class="card">
                    <div class="card-body">
                        <table class="table table-borderless table-shopping-cart">
                            <thead class="text-muted">
                                <tr class="small text-uppercase">
                                    <th scope="col">Product</th>
                                    <th scope="col" width="120">Quantity</th>
                                    <th scope="col" width="120">Price</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for cart_item in cart_items %}
                                <tr>
                                    <td>
                                        <figure class="itemside align-items-center">
                                            <div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm">
                                            </div>
                                            <figcaption class="info">
                                                <a href="{{ cart_item.product.get_product_url }}" class="title text-dark">{{cart_item.product.product_name }}</a>
                                                <p class="text-muted small">
                                                    {% if cart_item.variations.all %}
                                                    {% for item in cart_item.variations.all %}
                                                    {{ item.variation_category | capfirst }} : {{ item.variation_value | capfirst }} <br>
                                                    {% endfor %}
                                                    {% endif %}
                                                </p>
                                            </figcaption>
                                        </figure>
                                    </td>
                                    <td>
                                        <!-- col.// -->
                                        <label for="">{{ cart_item.quantity }}</label>
                                    </td>
                                    <td>
                                        <div class="price-wrap">
                                            <var class="price">$ {{ cart_item.sub_total }}</var>
                                            <small class="text-muted"> $ {{ cart_item.product.price }} each </small>
                                        </div> <!-- price-wrap .// -->
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <button type="submit" class="btn btn-primary btn-block" name="submit">Place Order</button>
                        <a href="{% url 'store:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
                    </form>
                    </div> <!-- card-body.// -->
                </div> <!-- card.// -->

            </aside> <!-- col.// -->


        </div> <!-- row.// -->
        <!-- ============================ COMPONENT 1 END .// ================================= -->

    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}