accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password/', views.reset_password, name='reset_password'),
    
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
]

carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    # the add_cart url is added so that the user's cart increased when he adds a cart
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    # This is the remove cart function which removes one particular product at a time
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    # This here removes everything from the cart
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    # this here is the checkout url
    path('checkout/', views.checkout, name='checkout'),
    
]

greatcart/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('category.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import  AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
# Create your models here.

class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError('User must have an email Address')
        
        if not username:
            raise ValueError('User must have an username')
        
        user = self.model(
            #Normalize the email address by lowercasing the domain part of it.
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name
        )
        
        
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    
    def create_superuser(self, first_name, last_name, username, email, password):
        user = self.create_user(
            email = self.normalize_email(email),
            first_name= first_name,
            last_name = last_name,
            username= username,
            password=password,
        )
        
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user
            




# This class creates users for your app
class Account(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=50)   
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=50)
    
    objects = MyAccountManager()
    # required fields to actually override the AbstractBaseUser
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)
    
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = [
        'username',
        'first_name',
        'last_name'
    ]
    
    def __str__(self) -> str:
        return self.email
    
    
    def has_perm(self, perm, obj=None):
       return self.is_admin
   
    def has_module_perms(self, add_label):
       return True

accounts/forms.py
from collections.abc import Mapping
from typing import Any
from django import forms
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList

from .models import *


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'Enter your password',
        #this is how you add a class field to your form field in django
        # class : form-control
    }))
    
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'Re-confirm your password',
    }))
    class Meta:
        model = Account
        fields = [
            'first_name',
            'last_name',
            'email',
            'phone_number',
            'password',
        ]
        
            
    def clean(self):
        """currently trying to override the 'clean' method"""
        cleaned_data = super(RegistrationForm, self).clean()
        
        # now let's get the password and the confirm password so that a user as to put the right password before they can be validated
        
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        
        # if len(password) and len(confirm_password) < 8:
        #     raise forms.ValidationError('Password length must be more than eigth.')
        
        if password != confirm_password:
            raise forms.ValidationError('Password does not match!')
    # time to overwrite the current init method of the registration form
    
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, *kwargs)
        # here, we are going to assign the placeholders to the form fields that we have
        
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter Your First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter Your Last Name'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Your Email Here'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Provide Your Phone Number'
        
        # looping through all the instances fields, and assiging them the class = form-control
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            
            

accounts/views.py
from django.shortcuts import render, redirect
from .forms import *

from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from .models import *
from carts.models import *
from store.views import _cart_id
# Create your views here.


# these are the imports you need to make for you to use the the token  to activate a user accounts
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage

import requests



def register(request):
    if request.method == 'POST':
        # this code executes when data is actually sent in a post request
        form = RegistrationForm(request.POST)
        # here i am getting the data being submitted by the new user, getting they word...
        # always remember, your form has to be valid before it is submitted, check always
        
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            phone_number = form.cleaned_data['phone_number']
            password = form.cleaned_data['password']
            # this here get the email and splits it in to two, taking the first index
            username = email.split("@")[0]
            
            user = Account.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email, password=password)
            # since we not using the phone_number as a means for validation, we can tie it manually
            user.phone_number = phone_number
            user.save()
            # this is where email is sent to the user to activate their accounts; many imports are needed for this...
            current_site = get_current_site(request)
            mail_subject = 'Please activate your account'
            message = render_to_string('accounts/account_verification_email.html', {
                'user': user,
                'domain' : current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            
            to_mail = email
            send_email = EmailMessage(mail_subject, message, to=[to_mail])
            send_email.send()
            # messages.success(request, 'Registration Successful. Check spam')
            # this code here gets the email and the command from the browser which will tell the user to actually activate their account
            return redirect('/accounts/login/?command=verification&email='+email)
            
            
            # after registration has been successful, show the 'Registration Successful to the user 'alert' '
            # messages.success(request, 'Registration Successful.')
            # return redirect('accounts:register')

    else:
         form = RegistrationForm()
        
    context = {
        'form': form
    }
    return render(request, 'accounts/register.html', context)


def login(request):
    # here is the code for when a user logs in
    if request.method == 'POST':
        # get the email and password submitted by the user
        email = request.POST['email']
        password = request.POST['password']
        
        # checks if it correspond to what is in the database and what the user submitted
        user = auth.authenticate(email=email, password=password)
        
        if user is not None:
            # here is the try-except block which checks the user cart_id and cartitem if they exists for a user.If it does, then assign it to the user account and update thier cartitem
            try:
                # this here i am trying to get the session id and assigns it to the cart_id. If yes...
                cart = Cart.objects.get(cart_id=_cart_id(request))
                # check if the cart exists or not
                is_cart_item_exists = CartItem.objects.filter(cart=cart).exists() #the cart in the database is equal to the cart up there
                
                if is_cart_item_exists:
                    # we get the cart item and then assigns it to the current user
                    cart_item = CartItem.objects.filter(cart=cart)
                    # we are going to loop over this cart item and then assign the looped item to the user
                    
                    # the current product variation the actually submits
                    product_variation = []
                    # we gotta loop over that cart_item up there, and append in to the product variation
                    for item in cart_item:
                        variations = item.variations.all()
                        # always remember to make it into a list
                        product_variation.append(list(variations))
                        
                    # filter this based on the user
                    cart_item = CartItem.objects.filter(user=user)
                    ex_var_list = []
                    id = []
                    for item in cart_item:
                        existing_variation = item.variations.all()
                        ex_var_list.append(list(existing_variation))
                        id.append(item.id)
                        
                    # now, it is time to loop over the product_variation aka current_variation saved by the user
                    for pr in product_variation:
                        if pr in ex_var_list:
                            # get the index of pr in the existing variation list
                            index = ex_var_list.index(pr)
                            item_id = id[index]
                            item = CartItem.objects.get(id=item_id)
                            # adds the current quantity if it matches, assign it to the current user and then save it
                            item.quantity += 1
                            item.user = user
                            item.save()
                        else:
                            # this here is for a user that hasn't logged in
                            cart_item = CartItem.objects.filter(cart=cart)
                            for item in cart_item:
                                # remember, the cartitem has a field 'user' which is a foreign key to the Account model
                                item.user = user  #item.user is access the database  and the user is the current user about to login
                                item.save()
            except:
                pass
            auth.login(request, user)
            messages.success(request, 'You are now logged in.')
            url = request.META.get('HTTP_REFERER')
            try:
                query = requests.utils.urlparse(url).query
                params = dict(x.split('=') for x in query.split('&'))
                if 'next' in params:
                    next_page = params['next']
                    return redirect(next_page)
            except:
                return redirect('accounts:dashboard')
        
        else:
            messages.error(request, 'Invalid login credentials')
            return redirect('accounts:login')
    
    
    return render(request, 'accounts/login.html')



@login_required(login_url='accounts:login')
def logout(request):
    auth.logout(request)
    messages.success(request,'You have logged out.')
    return redirect('accounts:login')


def activate(request, uidb64, token):
    # first we hae to use the try-except block
    try:
        # we are going to decode the user primary key
        
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None
        
    if user is not None and default_token_generator.check_token(user,token):
        user.is_active = True
        user.save()
        messages.success(request, 'Congratulations, your account has been activated.')
        return redirect('accounts:login')
    else:
        messages.error('Invalid activation link')
        return redirect('accounts:register')
    

@login_required(login_url='accounts:login')
def dashboard(request):
    return render(request, 'accounts/dashboard.html')


def forgot_password(request):
    if request.method == 'POST':
        email = request.POST['email']
        # this here checks if the accounts of the user exists
        if Account.objects.filter(email=email).exists():
            # this here is very case-sensitive
            user = Account.objects.get(email__exact=email)
            # reset user password by sending them an email
            current_site = get_current_site(request)
            mail_subject = 'Please activate your account'
            message = render_to_string('accounts/reset_password_verification.html', {
                'user': user,
                'domain' : current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            
            to_mail = email
            send_email = EmailMessage(mail_subject, message, to=[to_mail])
            send_email.send()
            
            messages.success(request, 'Password reset link has been sent to'+[email])
            
            return redirect('accounts:login')
        
        else:
            messages.error(request, 'Your Account does not exist!')
            return redirect('accounts:forgot_password')
        
    return render(request, 'accounts/forgot_password.html')


def reset_password_validate(request, uidb64, token):
    try:
    # we are going to decode the user primary key

accounts/templates/accounts/account_verification_email.html
{% autoescape off %}
Hi, {{ user.first_name }}

Please click on the below link to activate your account.

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

If you are not the one that requested for this, please ignore.

Thank you.

{% endautoescape off %}

accounts/templates/accounts/dashboard.html
{% extends 'category/base.html' %}


{% block content %}

<section class="section-conten padding-y bg">
    {% include 'category/includes/alerts.html' %}
    <div class="container">
        <div class="row">
            <aside class="col-md-3">
                <!--   SIDEBAR   -->
                <ul class="list-group">
                    <a class="list-group-item active" href="#"> My order history </a>
                    <a class="list-group-item" href="#"> Transactions </a>
                    <a class="list-group-item" href="#"> Return and refunds </a>
                    <a class="list-group-item" href="#">Settings </a>
                    <a class="list-group-item" href="#"> My Selling Items </a>
                    <a class="list-group-item" href="#"> Received orders </a>
                </ul>
                <br>
                <a class="btn btn-light btn-block" href="{% url 'accounts:logout' %}"> <i class="fa fa-power-off"></i>
                    <span class="text">Log
                        out</span> </a>
                <!--   SIDEBAR .//END   -->
            </aside>
            <main class="col-md-9">
                <article class="card">
                    <header class="card-header">
                        <strong class="d-inline-block mr-3">Order ID: 6123456789</strong>
                        <span>Order Date: 16 December 2018</span>
                    </header>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-8">
                                <h6 class="text-muted">Delivery to</h6>
                                <p>Michael Jackson <br>
                                    Phone +1234567890 Email: myname@pixsellz.com <br>
                                    Location: Home number, Building name, Street 123, Tashkent, UZB <br>
                                    P.O. Box: 100123
                                </p>
                            </div>
                            <div class="col-md-4">
                                <h6 class="text-muted">Payment</h6>
                                <span class="text-success">
                                    <i class="fab fa-lg fa-cc-visa"></i>
                                    Visa **** 4216
                                </span>
                                <p>Subtotal: $356 <br>
                                    Shipping fee: $56 <br>
                                    <span class="b">Total: $456 </span>
                                </p>
                            </div>
                        </div> <!-- row.// -->
                    </div> <!-- card-body .// -->
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <tr>
                                <td width="65">
                                    <img src="../images/items/1.jpg" class="img-xs border">
                                </td>
                                <td>
                                    <p class="title mb-0">Product name goes here </p>
                                    <var class="price text-muted">USD 145</var>
                                </td>
                                <td> Seller <br> Nike clothing </td>
                                <td width="250"> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="#"
                                        class="btn btn-light"> Details </a> </td>
                            </tr>
                        </table>
                    </div> <!-- table-responsive .end// -->
                </article> <!-- order-group.// -->
            </main>
        </div> <!-- row.// -->
    </div>


</section>
{% endblock content %}

accounts/templates/accounts/forgot_password.html
{% extends 'category/base.html' %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->

<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
    <div class="card mx-auto" style="max-width: 600px; margin-top:100px;">
        <div class="card-body">
            <h4 class="card-title mb-4">Forgot Password</h4>
            <form action="{% url 'accounts:forgot_password' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <input name="email" type="email" class="form-control" placeholder="Email Address">
                </div> <!-- form-group// -->

                <div class="form-group">
                    <a href="{% url 'accounts:login' %}" class="float-right">Got password? Login</a>

                </div> <!-- form-group form-check .// -->
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Submit </button>
                </div> <!-- form-group// -->
            </form>
        </div> <!-- card-body.// -->
    </div> <!-- card .// -->

    <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
    <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->

</section>
<!-- ========================= SECTION CONTENT END// ========================= -->



{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'category/base.html' %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->

<section class="section-conten padding-y" style="min-height:84vh">
    {% if request.GET.command %}
    <div class="container mx-auto text-center alert alert-info" role="alert"
        style="max-width: 1020px; margin-top:100px;">
        Thank you for registering with us. We have an activation link to [{{ request.GET.email }}]. Please verify it

        <br><br>

        Already verified? <a href="{% url 'accounts:register' %}">login</a>
    </div>

    {% else %}

    <!-- ============================ COMPONENT LOGIN   ================================= -->
    <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
        <div class="card-body">
            <h4 class="card-title mb-4">Sign in</h4>
            <form action="{% url 'accounts:login' %}" method="POST">
                {% csrf_token %}
                {% include 'category/includes/alerts.html' %}
                <div class="form-group">
                    <input name="email" type="email" class="form-control" placeholder="Email Address">
                </div> <!-- form-group// -->
                <div class="form-group">
                    <input name="password" type="password" class="form-control" placeholder="Password">
                </div> <!-- form-group// -->

                <div class="form-group">
                    <a href="{% url 'accounts:forgot_password' %}" class="float-right">Forgot password?</a>

                </div> <!-- form-group form-check .// -->
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Login </button>
                </div> <!-- form-group// -->
            </form>
        </div> <!-- card-body.// -->
    </div> <!-- card .// -->

    <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
    <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    {% endif %}

</section>
<!-- ========================= SECTION CONTENT END// ========================= -->



{% endblock content %}

accounts/templates/accounts/register.html
{% extends 'category/base.html' %}



{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

	<!-- ============================ COMPONENT REGISTER   ================================= -->
	<div class="card mx-auto" style="max-width:520px; margin-top:40px;">
		<article class="card-body">
			<header class="mb-4">
				<h4 class="card-title">Sign up</h4>
			</header>
			<form action="{% url 'accounts:register' %}" method="POST">
				{% csrf_token %}
				{% include 'category/includes/alerts.html' %}
				<div class="form-row">
					<div class="col form-group">
						<label>First name</label>
						{{ form.first_name }}
					</div> <!-- form-group end.// -->
					<div class="col form-group">
						<label>Last name</label>
						{{ form.last_name }}
					</div> <!-- form-group end.// -->
				</div> <!-- form-row end.// -->
				<!-- <div class="form-group">
					<label>Email</label>
					{{ form.email }}
					<small class="form-text text-muted">We'll never share your email with anyone else.</small>
				</div> form-group end.// -->
				<div class="form-row">
					<div class="form-group col-md-6">
						<label>Email Address</label>
						{{ form.email }}
					</div> <!-- form-group end.// -->
					<div class="form-group col-md-6">
						<label>Phone Number</label>
						{{ form.phone_number }}
					</div> <!-- form-group end.// -->
				</div> <!-- form-row.// -->
				<div class="form-row">
					<div class="form-group col-md-6">
						<label>Create password</label>
						{{ form.password }}
					</div> <!-- form-group end.// -->
					<div class="form-group col-md-6">
						<label>Repeat password</label>
						{{ form.confirm_password }}
					</div> <!-- form-group end.// -->
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-primary btn-block"> Register </button>
				</div> <!-- form-group// -->

				{{ form.email.errors }}
				{{ form.non_field_errors }}
			</form>
		</article><!-- card-body.// -->
	</div> <!-- card .// -->
	<p class="text-center mt-4">Have an account? <a href="{% url 'accounts:login' %}">Log In</a></p>
	<br><br>
	<!-- ============================ COMPONENT REGISTER  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}

accounts/templates/accounts/reset_password.html
{% extends 'category/base.html' %}

{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->

<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
    <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
        <div class="card-body">
            <h4 class="card-title mb-4">Reset Password</h4>
            <form action="{% url 'accounts:reset_password' %}" method="POST">
                {% csrf_token %}
                {% include 'category/includes/alerts.html' %}
                <div class="form-group">
                    <input name="password" type="password" class="form-control" placeholder="reset password">
                </div> <!-- form-group// -->
                <div class="form-group">
                    <input name="confirm_password" type="password" class="form-control" placeholder="confirm_password">
                </div> <!-- form-group// -->

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Reset </button>
                </div> <!-- form-group// -->
            </form>
        </div> <!-- card-body.// -->
    </div> <!-- card .// -->

    <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
    <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->

</section>
<!-- ========================= SECTION CONTENT END// ========================= -->



{% endblock content %}

accounts/templates/accounts/reset_password_verification.html
{% autoescape off %}
Hi, {{ user.first_name }}

As requested, please click on the below link to reset your password.

http://{{ domain }}{% url 'accounts:reset_password_validate' uidb64=uid token=token %}

If you are not the one that requested for this, please ignore.

Thank you.

{% endautoescape off %}